---
- name: the book of lazy
  hosts: ansible_client
  remote_user: root
  become: true
  tasks:
          - name: install httpd
            yum:
                    name: httpd
                    state: latest
          - name: run httpd
            service:
                    name: httpd
                    state: started
          - name: create content
            copy:
                    content: "Don't do the right things, do things right!"
                    dest: /var/www/html/index.html          
                                    
